settings:
  title: 'Status Page'
  url: 'https://status.lbenicio.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: lbenicio-main # unique identifier
    name: lbenicio.dev
    description: 'Personal website.' # default=empty
    url: 'https://lbenicio.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: lbenicio-blog
    name: blog.lbenicio.dev
    description: 'Personal blog.'
    url: 'https://blog.lbenicio.dev'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: lbenicio-paste
    name: paste.lbenicio.dev
    description: 'Personal Gist server.'
    url: 'https://paste.lbenicio.dev'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: lbenicio-pgp
    name: pgp.lbenicio.dev
    description: 'Pgp key server.'
    url: 'https://pgp.lbenicio.dev'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
